CONFIG:
  zmin: 1.0
  rebinWidth: 0.05
  zCharacteristic: 5.0
  fontsize: 8.0
  eazy_outfolder: "eazy-output"
  colorAfterScore: True
MOSAICZ:
  mosTiling: 4.0
  zMax: 16.5
  mm: '1/25.4'
  figwidth: '183*mm'
  DPI: 500
  ro: 2